### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by promitheus7** [raphiniert-com/ra-data-postgrest#36]
Would it make more sense to release a version 3.x and 4.x of this repo s.t. the delineation to match versions with `react-admin`?

**Comment by scheiblr** [comment]
Thank you for that idea. That is for sure something to think about if v3.x should be further maintained. I do not really see the requirement for that right now, as RA 3.x got its last update on [05 Apr 2022](https://github.com/marmelab/react-admin/releases/tag/v3.19.11). Thus, I would say we also go along with this DP and people should update. Anyways, I do not really expect new features to come, but code improvments, which I have on my list (but not yet took the time to implement).

Apart from that, I think we should neglect the duplicated DP from the marmelab page again and maybe from npm as well. This would otherwise lead to confusion and unfocused contributions, which we should prevent for the good of the project.

**Comment by promitheus7** [comment]
Yup let's do it, I actively use this so would be happy to contribute.

**Comment by promitheus7** [comment]
Added a `deprecated` to the README for my version in case anyone is confused as well.

**Comment by scheiblr** [comment]
Perfect. I would suggest you just drop me an email on my [private web page's contact form](https://raphiniert.com/#contact) and we setup an appointment. You could already sent me your time zone and suggestions when you've got time.

**Comment by promitheus7** [comment]
Sent
