### ISSUE TITLE
Allow column filtering

### ISSUE THREAD

**Issue by christiaanwesterbeek** [raphiniert-com/ra-data-postgrest#56]
From the Postgrest docs:

> When certain columns are wide (such as those holding binary data), it is more efficient for the server to withhold them in a response. The client can specify which columns are required using the select parameter.

https://postgrest.org/en/stable/api.html#vertical-filtering-columns

Let's do this.

**Comment by dnk8n** [comment]
Maybe in a few weeks I can lend a hand. I don't know much about Haskell, but willing to learn.

**Comment by dnk8n** [comment]
Oh great. That would be useful in the docs. Once I get my project
delivered, happy to give back in the form of outstanding docs or features.

**Comment by christiaanwesterbeek** [comment]
It's not in the docs, because that feature is not in this repo yet. Just in my local copy which I can't merge here.

**Comment by dnk8n** [comment]
Yeah, I realized that this morning. My bad. I edited my comment but because it was an email reply code highlighting doesn't work. So I will include it here:

Potentially in future, there may be a more generic way of handling all of postgREST's 'meta' features using the same schema as postgrest does so there is no further mappings other than pagination, sort and filter.

That way, there doesn't need to be a PR each time postgrest adds a new option. Just like postgREST introspects from Postgres, this data provider can introspect from postgREST.

e.g.

For reference:

```js
export interface GetListParams {
    pagination: PaginationPayload;
    sort: SortPayload;
    filter: any;
    meta?: any;
}
```

where:

```js
dataprovider.useGetList(
    'films',
    {
        sort: {
            field: 'date',
            order: 'asc' 
        },
        filter: {},
        meta: {
            select: ['title', {'directors': ['id', 'last_name']}]
        }
);
```
or
```js
<List sort={{ field: 'date', order: 'asc' }} meta={{ select: ['title', {'directors': ['id', 'last_name']}] }} >
```

maps to: 
`GET /films?select=title,directors(id,last_name)&order=date.asc`

or

`GET /films?select=title,directors(id,last_name)&order=date.asc&limit=10&offset=0` (note that pagination is handled by default in second case)

The [API docs](https://postgrest.org/en/stable/api.html) have all the possibilities, but from what I can tell they all fit a key with list of values format

**Comment by scheiblr** [comment]
Try the new alpha version, which I just released :)

**Comment by dnk8n** [comment]
I will let you know once I have. I got to release a stable version of the admin panel I am building. Behind on many tests which I am busy implementing, then I will switch to the alpha version and give some feedback.

**Comment by dnk8n** [comment]
Trying the latest 2.0.0-alpha.1 release. This feature works nicely so far. Very useful to avoid over-fetching from the API.
